import { centuriesFromJ2000 } from '../time.js';
import { nutation } from '../nutation.js';

/**
 * Ayanāṁśa modes Jade supports. Each maps 1:1 onto a Swiss Ephemeris sidereal
 * mode so the two providers can never silently disagree about which zodiac
 * they are in.
 *
 * Never default this silently anywhere in the app — CLAUDE.md, non-negotiable #3.
 */
export type AyanamsaMode =
  | 'lahiri'
  | 'lahiri_true_chitra'
  | 'raman'
  | 'krishnamurti'
  | 'yukteshwar'
  | 'fagan_bradley'
  | 'suryasiddhanta'
  | 'custom';

export const AYANAMSA_LABELS: Record<AyanamsaMode, string> = {
  lahiri: 'Lahiri (Chitrapakṣa)',
  lahiri_true_chitra: 'True Citrā',
  raman: 'B. V. Raman',
  krishnamurti: 'Krishnamurti (KP)',
  yukteshwar: 'Yukteshwar',
  fagan_bradley: 'Fagan–Bradley',
  suryasiddhanta: 'Sūrya Siddhānta',
  custom: 'Custom offset',
};

/**
 * Cubic fits of the MEAN ayanāṁśa (nutation excluded), degrees, in Julian
 * centuries of TT from J2000.
 *
 * Fitted by least squares against Swiss Ephemeris over 1700–2200 at 3000
 * sample points. Measured max error for `lahiri`: 0.0002 arcsec — i.e. this
 * reproduces Swiss Ephemeris rather than approximating precession
 * independently. Regenerate with `python3 scripts/generate_fixtures.py --ayanamsa`.
 *
 * The v0 prototype used a bare precession polynomial with no reference epoch
 * calibration and drifted by arcminutes; that is why this exists.
 */
/**
 * Cubic fits to each mode's MEAN ayanāṁśa, 1700–2200.
 *
 * Generated by `scripts/generate_fixtures.py --ayanamsa` against Swiss
 * Ephemeris and pasted here with the measured residual beside each line, so
 * the number in this file can be checked against the run that produced it.
 * `test/ayanamsa.test.ts` re-checks all of them against the oracle fixture.
 *
 * Mean rather than apparent: nutation in longitude is removed before fitting
 * and added back by `ayanamsa()` when asked for. Fitting the apparent value
 * would bake an 18.6-year wobble into a smooth polynomial and leave a residual
 * around 17″ — larger than every budget in the published accuracy table.
 *
 * **True Citrā is deliberately absent.** It fits to 20.7″, which is four times
 * the ascendant's whole budget, because the mode is not a polynomial in time
 * at all: it pins Spica to exactly 180° and therefore tracks that star's
 * proper motion and the fixed-star model behind it. A cubic cannot represent
 * that, and a 20″ ayanāṁśa is a visibly wrong chart rather than a slightly
 * wrong one. It stays declared and throwing until it is implemented properly,
 * which means computing Spica rather than approximating the result.
 */
const MEAN_AYANAMSA_FIT: Partial<Record<AyanamsaMode, readonly [number, number, number, number]>> =
  {
    // [constant, ×T, ×T², ×T³]            // max residual vs Swiss Ephemeris
    lahiri: [23.85709236051419, 1.396887925035841, 0.0003070810067976883, 1.5866507414720884e-8], // 0.00022″
    raman: [22.410791047106386, 1.3968880452015549, 0.00030704760827101663, 1.572408719112672e-8], // 0.00022″
    krishnamurti: [
      23.76024004710637, 1.3968880452015557, 0.0003070476082803991, 1.572409054925839e-8,
    ], // 0.00022″
    yukteshwar: [
      22.47880303458805, 1.396888045201554, 0.0003070476082753951, 1.5724086799262612e-8,
    ], // 0.00022″
    fagan_bradley: [
      24.74030000123749, 1.3968879394333966, 0.00030707732031501665, 1.5850135563711464e-8,
    ], // 0.00022″
    suryasiddhanta: [
      20.895058888934468, 1.3968835226164666, 0.0003061897024161798, 1.6378666249783412e-8,
    ], // 0.00021″
  };

/**
 * The modes that can actually be computed today.
 *
 * Derived from the fit table rather than written out again, so fitting Raman
 * is one edit: add its coefficients above and it becomes selectable, guarded
 * and documented everywhere at once. A second hand-kept list would be a second
 * thing to forget.
 *
 * `custom` is included whenever Lahiri is, because a custom offset is defined
 * as a constant shift from Lahiri's precession rate — it has no fit of its own
 * and cannot outlive the one it borrows.
 */
export const FITTED_AYANAMSAS: readonly AyanamsaMode[] = [
  ...(Object.keys(MEAN_AYANAMSA_FIT) as AyanamsaMode[]),
  ...(MEAN_AYANAMSA_FIT.lahiri ? (['custom'] as const) : []),
];

export interface AyanamsaOptions {
  readonly mode: AyanamsaMode;
  /** Only used when mode === 'custom': degrees at J2000. */
  readonly customAtJ2000?: number;
  /**
   * Include nutation in longitude. TRUE is correct when subtracting from
   * apparent (true-equinox-of-date) tropical longitudes, which is what both
   * Jade providers produce. Swiss Ephemeris does the same internally.
   */
  readonly includeNutation?: boolean;
}

/**
 * Ayanāṁśa in degrees at a Terrestrial Time Julian Day.
 *
 * @throws if the mode has no fit yet — deliberately. A wrong zodiac is worse
 * than a missing feature, so unimplemented modes fail loudly rather than
 * falling back to Lahiri.
 */
export function ayanamsa(jdTt: number, options: AyanamsaOptions): number {
  const t = centuriesFromJ2000(jdTt);

  let mean: number;
  if (options.mode === 'custom') {
    if (options.customAtJ2000 === undefined) {
      throw new Error("ayanamsa: mode 'custom' requires customAtJ2000");
    }
    const lahiri = MEAN_AYANAMSA_FIT.lahiri!;
    // Custom offsets are defined as a constant shift from Lahiri's precession rate.
    mean = options.customAtJ2000 + lahiri[1] * t + lahiri[2] * t * t + lahiri[3] * t * t * t;
  } else {
    const fit = MEAN_AYANAMSA_FIT[options.mode];
    if (!fit) {
      throw new Error(
        `ayanamsa: mode '${options.mode}' is declared but not yet fitted. ` +
          'Add its coefficients via scripts/generate_fixtures.py --ayanamsa ' +
          'rather than falling back to another zodiac.',
      );
    }
    mean = fit[0] + fit[1] * t + fit[2] * t * t + fit[3] * t * t * t;
  }

  if (options.includeNutation === false) return mean;
  return mean + nutation(jdTt).dPsi;
}
