#!/usr/bin/env python3
"""
Differential oracle: aṣṭakūṭa (guṇa milāna), via PyJHora.

Aṣṭakūṭa depends on nothing but each person's Moon nakṣatra and pāda, which
means the whole technique has exactly 108 x 108 = 11,664 possible inputs. That
is small enough to enumerate, so this writes out **every** one of them rather
than a sample: there is no untested corner left for a wrong table row to hide
in.

Encoding: each kūṭa is 108 lines of 108 characters. A character is the score
doubled and written in base 36 — scores are always multiples of a half, and the
largest is nāḍī at 8, so doubled they span 0..16 and fit in one digit. Row
index is the first person, column the second; both run nakṣatra-major,
`(nakshatra - 1) * 4 + (pada - 1)`.

The alternative — arrays of numbers — is the same information at four times the
bytes, and nobody reads either by eye.

See scripts/oracle_jhora.py for the licence position. PyJHora is AGPL, is a
developer tool, and never ships.

USAGE
-----
    pip install PyJHora
    python3 scripts/oracle_ashtakuta.py            # write fixtures
    python3 scripts/oracle_ashtakuta.py --check    # fail if they would change
"""

from __future__ import annotations

import argparse
import json
import pathlib
import string
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "packages/astro/test/fixtures/jhora-ashtakuta.json"

DIGITS = string.digits + string.ascii_lowercase  # base 36

# The order compatibility_score() returns them in, which is not the order they
# are usually recited in. Identified by their maxima, which are unique.
KUTA_ORDER = ["varna", "vasya", "gana", "tara", "yoni", "maitri", "bhakuta", "nadi"]
MAXIMA = {
    "varna": 1,
    "vasya": 2,
    "gana": 6,
    "tara": 3,
    "yoni": 4,
    "maitri": 5,
    "bhakuta": 7,
    "nadi": 8,
}


def encode(score: float) -> str:
    doubled = round(score * 2)
    if not 0 <= doubled < 36:
        raise ValueError(f"score {score} does not fit one base-36 digit")
    return DIGITS[doubled]


def build() -> dict:
    from jhora.horoscope.match.compatibility import Ashtakoota

    states = [(n, p) for n in range(1, 28) for p in range(1, 5)]
    rows: dict[str, list[str]] = {k: [] for k in KUTA_ORDER}
    totals: list[str] = []

    for bn, bp in states:
        line: dict[str, list[str]] = {k: [] for k in KUTA_ORDER}
        total_line: list[str] = []
        for gn, gp in states:
            score = Ashtakoota(bn, bp, gn, gp, method="North").compatibility_score()
            for i, key in enumerate(KUTA_ORDER):
                line[key].append(encode(score[i]))
            # The total is 0..36, so it needs two base-36 digits at half
            # resolution (0..72). Written as a plain number instead.
            total_line.append(f"{score[8]:g}")
        for key in KUTA_ORDER:
            rows[key].append("".join(line[key]))
        totals.append(",".join(total_line))

    return {
        "generator": "PyJHora (Jagannātha Hora), AGPL-3.0 — developer tool, never shipped",
        "method": "North",
        "note": (
            "Generated by scripts/oracle_ashtakuta.py. Do not hand-edit. Every one "
            "of the 11,664 possible pairings, not a sample. Index is "
            "(nakshatra - 1) * 4 + (pada - 1), 0-based, for both axes. Each "
            "character is the score doubled, base 36."
        ),
        "maxima": MAXIMA,
        "states": len(states),
        "kutas": rows,
        "totals": totals,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    fresh = json.dumps(build(), indent=2, ensure_ascii=False) + "\n"

    if args.check:
        if not OUT.exists():
            print(f"{OUT.relative_to(REPO)} does not exist. Run without --check.")
            return 1
        if OUT.read_text() != fresh:
            print(f"{OUT.relative_to(REPO)} is out of date. Regenerate and review the diff.")
            return 1
        print(f"{OUT.relative_to(REPO)} is current.")
        return 0

    OUT.write_text(fresh)
    print(f"wrote {OUT.relative_to(REPO)}: 11,664 pairings")
    return 0


if __name__ == "__main__":
    sys.exit(main())
