import report from '@jade/astro/accuracy-report.json';
import { DELTA_T_RELAXATION, baseToleranceArcsec, toleranceKeyFor } from '@jade/astro';

/**
 * The published accuracy table, assembled from the two files that decide it.
 *
 * ## Why this is not a hand-written list
 *
 * It was one. The page promised the Sun within 1.0″ while the suite enforced
 * 2.0″ and the shipped provider measured 3.8″ — three numbers, three places,
 * and the one a customer could read was the furthest from the truth. The fix
 * was two halves: `tolerances.ts` in the astro package, so the test and the
 * page assert against one table, and this module, so the page prints what the
 * generator actually measured rather than what anybody remembered.
 *
 * `accuracy-report.json` is regenerated by the accuracy suite against Swiss
 * Ephemeris. If a measurement regresses, the number on the public page moves
 * with it. That is the point: a published promise that cannot be checked is
 * marketing, and a published promise that updates itself is a test.
 *
 * ## The two bands
 *
 * Budgets are relaxed outside 1900–2050, where Jade's ΔT polynomial and Swiss
 * Ephemeris's diverge by seconds of *time* — and the Moon moves 33″ a minute,
 * so a 69″ disagreement on a 2099 chart is a clock difference of about two
 * seconds, not a wrong position. The two bands are shown separately and
 * labelled, because a relaxed budget shown as a met one is the same lie in a
 * different direction.
 */

export interface AccuracyRow {
  /** The quantity as the report names it. */
  readonly quantity: string;
  /** The enforced budget inside the observed ΔT era, in arcseconds. */
  readonly budget: number;
  /** The worst measurement across the fixture set. */
  readonly worst: number;
  /** Which fixture produced it. */
  readonly chart: string;
  /** True when the worst case comes from a chart outside 1900–2050. */
  readonly extrapolated: boolean;
  /**
   * True when the measurement needed the ΔT relaxation to pass — that is, it
   * exceeds the unrelaxed budget and came from outside the observed era.
   *
   * Deliberately narrower than `extrapolated`. Marking every pre-1900 row
   * would imply the budget was widened to let it through when it was not, and
   * a mark that appears where it was not needed teaches a reader to ignore it
   * where it was.
   */
  readonly relaxed: boolean;
}

/** Fixtures outside the era of observed ΔT, named so a row can say so. */
const EXTRAPOLATED_CHARTS = new Set(['future-2099', 'pre-1900-london', 'nineteenth-century-us']);

/**
 * Display order: the frame first, then the angles, then the bodies a reader
 * came to check. Not the report's own order, which is by error size — that
 * would put the worst number at the top of a page about trustworthiness, and
 * rank the Moon above the ascendant for no reason a reader would recognise.
 */
const ORDER = [
  '~ayanamsa',
  '~dPsi',
  '~obliquity',
  'Ascendant',
  'Midheaven',
  'Sun',
  'Moon',
  'Mercury',
  'Venus',
  'Mars',
  'Jupiter',
  'Saturn',
  'Rahu',
  'TrueNode',
  'Uranus',
  'Neptune',
  'Pluto',
];

/** How the report spells a quantity, said the way the page should say it. */
const LABEL: Record<string, string> = {
  '~ayanamsa': 'Ayanāṁśa',
  '~dPsi': 'Nutation in longitude',
  '~obliquity': 'Obliquity',
  Rahu: 'Rāhu and Ketu (mean)',
  TrueNode: 'True node',
};

export function labelFor(quantity: string): string {
  return LABEL[quantity] ?? quantity;
}

export interface AccuracyReport {
  readonly generatedAgainst: string;
  readonly provider: string;
  readonly precisionClass: string;
  readonly charts: number;
  readonly rows: readonly AccuracyRow[];
  /** The relaxation multiplier, so the page can state it rather than imply it. */
  readonly relaxation: number;
}

export function accuracyReport(): AccuracyReport {
  const byQuantity = new Map(report.worstCase.map((one) => [one.quantity, one]));

  const rows: AccuracyRow[] = [];
  for (const quantity of ORDER) {
    const measured = byQuantity.get(quantity);
    /* A quantity in the display order but not in the report is a generator
       change, not a page bug — skip it rather than printing a blank row. */
    if (!measured) continue;
    /* Only quantities with a budget are published; an unbudgeted one is not a
       promise and must not be shown as though it were. */
    if (toleranceKeyFor(quantity) === null) continue;
    const budget = baseToleranceArcsec(quantity);
    const extrapolated = EXTRAPOLATED_CHARTS.has(measured.chart);
    rows.push({
      quantity,
      budget,
      worst: measured.error,
      chart: measured.chart,
      extrapolated,
      relaxed: extrapolated && measured.error > budget,
    });
  }

  return {
    generatedAgainst: report.generatedAgainst,
    provider: report.provider,
    precisionClass: report.precisionClass,
    charts: report.charts,
    rows,
    relaxation: DELTA_T_RELAXATION,
  };
}

/** Arcseconds, said the way an astrologer writes them. */
export function arcsec(value: number): string {
  if (value < 0.01) return `${value.toFixed(4)}″`;
  if (value < 1) return `${value.toFixed(3)}″`;
  if (value < 10) return `${value.toFixed(2)}″`;
  return `${value.toFixed(1)}″`;
}
